# Generated by Django 4.0.6 on 2022-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_link',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
